#!/bin/bash
# Benchmark: EDZ binary bitset format vs SEDS text format.
#
# Measures three things for each input size:
#
#   1. vcf2eds write speed — SEDS vs EDZ output for the same EDS content.
#      Uses genrandomeds to produce a synthetic VCF-shaped input (via the
#      eds+seds pair as a stand-in), then pipes through msa2eds which also
#      writes source files, so we can compare the two formats at write time.
#
#      Actually vcf2eds needs a real VCF+FASTA. Instead we benchmark vcf2eds
#      on small synthetic data vs eds2leds which exercises seds read/write.
#      The cleanest proxy: compare eds2leds --linear with SEDS (default) vs
#      an EDZ input file generated by vcf2eds --source-format edz.
#
#   2. EDS→l-EDS linear throughput with SEDS source vs EDZ source.
#      genrandomeds always writes SEDS; we convert a copy to EDZ via
#      vcf2eds round-trip, then compare eds2leds --linear on each.
#      Note: eds2leds reads sources for merge intersection; EDZ is decoded
#      on-demand via the LRU cache, so throughput difference reveals
#      EDZ decode overhead vs SEDS parse overhead.
#
#   3. Source file size ratio: SEDS bytes / EDZ bytes (compression factor).
#      For N paths, EDZ uses ceil(N/8) bytes per entry vs N×5 bytes average
#      for SEDS text with 4-digit path IDs.  Expect ~8× for 2504 paths.
#
# Fixed: ref_size_mb (from caller), l=5, variability=0.05, min-context=5.
# The variability=0.05 ensures non-trivial source diversity in the output.

run_scenario_edz_format() {
    local tmpdir="$1" csv="$2" ts="$3" preset="$4" n_reps="$5"
    shift 5
    local sizes_mb=("$@")

    local gen_tool eds_tool vcf_tool stats_tool
    gen_tool=$(find_tool genrandomeds)      || { bench_err "genrandomeds not found";   return 1; }
    eds_tool=$(find_tool eds2leds)          || { bench_err "eds2leds not found";        return 1; }
    vcf_tool=$(find_tool vcf2eds)           || { bench_err "vcf2eds not found";         return 1; }
    stats_tool=$(find_tool edsparser-stats) || { bench_err "edsparser-stats not found"; return 1; }

    local var=0.05
    local l=5
    local seed=700

    for ref_size_mb in "${sizes_mb[@]}"; do
        local base="$tmpdir/edz_${ref_size_mb}mb"
        local seds_eds="${base}_seds.eds"
        local seds_seds="${base}_seds.seds"

        # ── Generate synthetic EDS + SEDS via genrandomeds ─────────────────
        bench_log "generating input for edz_format (ref=${ref_size_mb}MB, var=${var}) ..."
        "$gen_tool" --ref-size-mb "$ref_size_mb" --seed $((seed++)) \
            --variability "$var" --min-context "$l" \
            -o "$seds_eds" 2>/dev/null

        local seds_size_mb edz_size_mb
        seds_size_mb=$(file_size_mb "$seds_seds")

        # ── Convert SEDS → EDZ using eds2leds as a passthrough ─────────────
        # eds2leds --linear with l=1 (compliant input, 0 merges) will copy the
        # SEDS verbatim to its output seds file.  We can't use vcf2eds here
        # because we don't have a VCF file.  Instead, use edsparser-stats which
        # reads all source entries — it serves as the read-speed benchmark.
        #
        # For the EDZ write benchmark, use eds2leds to write a temporary SEDS
        # copy, then manually convert it: currently there is no "seds2edz" tool,
        # but vcf2eds --source-format edz writes EDZ.  We use a small Python
        # helper instead to convert SEDS→EDZ via the library's static API — but
        # that requires a Python binding which doesn't exist yet.
        #
        # PRACTICAL APPROACH: benchmark what we can do today:
        #   - Read benchmark: edsparser-stats (reads every source entry via cache)
        #   - Size ratio: reported for SEDS only (EDZ ratio is theoretical)
        #   - Write benchmark: eds2leds --linear with SEDS output (production path)
        # A separate sub-scenario writes EDZ via vcf2eds on synthetic VCF data.

        # ── 1. Source read speed: edsparser-stats (reads all SEDS entries) ──
        local scenario_stats="edz_format_stats_seds_${ref_size_mb}mb"
        bench_log "scenario=$scenario_stats  (N=$n_reps)"
        run_bench_scenario "$n_reps" \
            "$stats_tool" -i "$seds_eds" -s "$seds_seds"

        local eds_size_mb throughput_stats
        eds_size_mb=$(file_size_mb "$seds_eds")
        throughput_stats=$(compute_throughput "$seds_size_mb" "$BENCH_RUNTIME_S")

        write_csv_row "$csv" "$ts" "$preset" "$scenario_stats" \
            "edsparser-stats(seds)" "$seds_size_mb" "$n_reps" "$throughput_stats"
        bench_log "  [stats/seds] median=${BENCH_RUNTIME_S}s  ±${BENCH_RUNTIME_STDDEV_S}s  mem=${BENCH_PEAK_MEMORY_MB}MB  throughput=${throughput_stats}MB/s"

        # ── 2. eds2leds linear write speed (SEDS output — production path) ──
        local out_leds="${base}_leds.leds"
        local out_leds_seds="${base}_leds.seds"
        local scenario_write="edz_format_leds_seds_${ref_size_mb}mb"
        bench_log "scenario=$scenario_write  (N=$n_reps)"
        run_bench_scenario "$n_reps" \
            "$eds_tool" -i "$seds_eds" -s "$seds_seds" -o "$out_leds" -l "$l"

        local throughput_write
        throughput_write=$(compute_throughput "$eds_size_mb" "$BENCH_RUNTIME_S")

        write_csv_row "$csv" "$ts" "$preset" "$scenario_write" \
            "eds2leds(seds_out)" "$eds_size_mb" "$n_reps" "$throughput_write"
        bench_log "  [leds/seds] median=${BENCH_RUNTIME_S}s  ±${BENCH_RUNTIME_STDDEV_S}s  mem=${BENCH_PEAK_MEMORY_MB}MB  throughput=${throughput_write}MB/s"

        # ── 3. SEDS file sizes (log for ratio comparison) ──────────────────
        local out_seds_size
        out_seds_size=$(file_size_mb "$out_leds_seds" 2>/dev/null || echo "0.000")
        bench_log "  [sizes] input EDS=${eds_size_mb}MB  input SEDS=${seds_size_mb}MB  l-EDS SEDS=${out_seds_size}MB"
        bench_log "  [ratio] SEDS/EDS = $(awk "BEGIN { printf \"%.1f\", $seds_size_mb / $eds_size_mb }")×"

        # ── 4. vcf2eds EDZ write on synthetic single-chromosome VCF ────────
        # Generate a minimal VCF+FASTA pair for a tiny genome so we can
        # benchmark vcf2eds --source-format seds vs --source-format edz.
        # Skip for large sizes to keep bench time reasonable.
        if awk "BEGIN { exit ($ref_size_mb > 10) ? 0 : 1 }"; then
            bench_log "  (vcf2eds EDZ sub-scenario skipped for ref=${ref_size_mb}MB — too large)"
        else
            local vcf_base="$tmpdir/edz_vcf_${ref_size_mb}mb"
            local vcf_file="${vcf_base}.vcf"
            local fasta_file="${vcf_base}.fa"
            local vcf_eds_seds="${vcf_base}_seds.eds"
            local vcf_src_seds="${vcf_base}.seds"
            local vcf_eds_edz="${vcf_base}_edz.eds"
            local vcf_src_edz="${vcf_base}.edz"

            # Build a synthetic single-chrom VCF with ~var*ref_size*1M variants
            # and 10 samples using awk.
            local n_bases=$(( ref_size_mb * 1024 * 1024 ))
            local n_samples=10
            local n_variants=$(awk "BEGIN { printf \"%d\", $n_bases * $var }")

            bench_log "  generating synthetic VCF (${ref_size_mb}MB genome, ${n_samples} samples, ${n_variants} variants) ..."
            _generate_synthetic_vcf "$fasta_file" "$vcf_file" "$n_bases" "$n_samples" "$n_variants"

            # vcf2eds SEDS
            local sc_vcf_seds="edz_format_vcf_seds_${ref_size_mb}mb"
            bench_log "  scenario=$sc_vcf_seds  (N=$n_reps)"
            run_bench_scenario "$n_reps" \
                "$vcf_tool" -i "$vcf_file" -r "$fasta_file" \
                    -o "$vcf_eds_seds" -s "$vcf_src_seds" \
                    --source-format seds 2>/dev/null

            local vcf_fasta_size
            vcf_fasta_size=$(file_size_mb "$fasta_file")
            local tp_vcf_seds
            tp_vcf_seds=$(compute_throughput "$vcf_fasta_size" "$BENCH_RUNTIME_S")
            write_csv_row "$csv" "$ts" "$preset" "$sc_vcf_seds" \
                "vcf2eds(seds)" "$vcf_fasta_size" "$n_reps" "$tp_vcf_seds"
            bench_log "  [vcf/seds] median=${BENCH_RUNTIME_S}s  ±${BENCH_RUNTIME_STDDEV_S}s  mem=${BENCH_PEAK_MEMORY_MB}MB  tp=${tp_vcf_seds}MB/s"

            # vcf2eds EDZ
            local sc_vcf_edz="edz_format_vcf_edz_${ref_size_mb}mb"
            bench_log "  scenario=$sc_vcf_edz  (N=$n_reps)"
            run_bench_scenario "$n_reps" \
                "$vcf_tool" -i "$vcf_file" -r "$fasta_file" \
                    -o "$vcf_eds_edz" -s "$vcf_src_edz" \
                    --source-format edz 2>/dev/null

            local tp_vcf_edz
            tp_vcf_edz=$(compute_throughput "$vcf_fasta_size" "$BENCH_RUNTIME_S")
            write_csv_row "$csv" "$ts" "$preset" "$sc_vcf_edz" \
                "vcf2eds(edz)" "$vcf_fasta_size" "$n_reps" "$tp_vcf_edz"
            bench_log "  [vcf/edz]  median=${BENCH_RUNTIME_S}s  ±${BENCH_RUNTIME_STDDEV_S}s  mem=${BENCH_PEAK_MEMORY_MB}MB  tp=${tp_vcf_edz}MB/s"

            # Size comparison
            local seds_bytes edz_bytes ratio
            seds_bytes=$(stat -c "%s" "$vcf_src_seds" 2>/dev/null || echo 1)
            edz_bytes=$( stat -c "%s" "$vcf_src_edz"  2>/dev/null || echo 1)
            ratio=$(awk "BEGIN { printf \"%.1f\", $seds_bytes / $edz_bytes }")
            bench_log "  [vcf size] SEDS=$(awk "BEGIN { printf \"%.3f\", $seds_bytes/1048576 }")MB  EDZ=$(awk "BEGIN { printf \"%.3f\", $edz_bytes/1048576 }")MB  ratio=${ratio}×"
        fi

        echo ""
    done
}

# Generate a minimal FASTA + VCF pair for benchmarking.
# Genome: simple repeating ACGT…; variants: SNPs at every ~(1/var) position.
_generate_synthetic_vcf() {
    local fasta_out="$1" vcf_out="$2" n_bases="$3" n_samples="$4" n_variants="$5"

    # FASTA: repeat ACGT
    {
        echo ">chr1"
        python3 - "$n_bases" <<'PYEOF'
import sys
n = int(sys.argv[1])
bases = "ACGT"
line_len = 60
chunk = (bases * ((line_len // 4) + 1))[:line_len]
full_lines, rem = divmod(n, line_len)
for _ in range(full_lines):
    print(chunk)
if rem:
    print((bases * ((rem // 4) + 1))[:rem])
PYEOF
    } > "$fasta_out"

    # VCF: SNPs at evenly-spaced positions, 10 samples with GT 0|1 / 1|0 / 0|0
    {
        echo "##fileformat=VCFv4.1"
        echo "##contig=<ID=chr1,length=$n_bases>"
        printf "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT"
        for (( s=1; s<=n_samples; s++ )); do printf "\tS%d" "$s"; done
        echo

        python3 - "$n_bases" "$n_variants" "$n_samples" <<'PYEOF'
import sys
n_bases, n_variants, n_samples = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
bases = "ACGT"
step = max(1, n_bases // n_variants)
alt_map = {"A": "G", "C": "T", "G": "A", "T": "C"}
pos = step
for i in range(n_variants):
    if pos >= n_bases:
        break
    ref = bases[(pos - 1) % 4]
    alt = alt_map[ref]
    gts = []
    for s in range(n_samples):
        # Cycle through: 0|1, 1|0, 0|0 so ~2/3 have the variant
        cycle = s % 3
        gts.append("0|1" if cycle == 0 else "1|0" if cycle == 1 else "0|0")
    print(f"chr1\t{pos}\t.\t{ref}\t{alt}\t.\tPASS\t.\tGT\t" + "\t".join(gts))
    pos += step
PYEOF
    } > "$vcf_out"
}
